// Categories for AI Tools for Teachers
const categories = [
  {
    name: "Lesson Planning",
    slug: "lesson-planning",
    description: "AI tools that help teachers plan, structure, and create lesson plans in seconds.",
    icon: "📋",
    sortOrder: 1,
  },
  {
    name: "Quiz & Assessment",
    slug: "quiz-assessment",
    description: "Tools for generating quizzes, tests, and assessments automatically with AI.",
    icon: "📝",
    sortOrder: 2,
  },
  {
    name: "Grading & Feedback",
    slug: "grading-feedback",
    description: "AI grading tools that provide instant feedback on student work.",
    icon: "✅",
    sortOrder: 3,
  },
  {
    name: "Presentations",
    slug: "presentations",
    description: "Create beautiful presentations and slides with AI assistance.",
    icon: "📊",
    sortOrder: 4,
  },
  {
    name: "Content Creation",
    slug: "content-creation",
    description: "Generate worksheets, handouts, reading materials, and educational content.",
    icon: "✏️",
    sortOrder: 5,
  },
  {
    name: "Classroom Management",
    slug: "classroom-management",
    description: "Tools to manage classroom behavior, attendance, and communication.",
    icon: "🏫",
    sortOrder: 6,
  },
  {
    name: "Video & Multimedia",
    slug: "video-multimedia",
    description: "AI video creation, editing, and multimedia tools for educators.",
    icon: "🎬",
    sortOrder: 7,
  },
  {
    name: "Language Learning",
    slug: "language-learning",
    description: "AI-powered tools for teaching and learning languages.",
    icon: "🌍",
    sortOrder: 8,
  },
  {
    name: "Differentiation & Personalization",
    slug: "differentiation",
    description: "Adapt content to different reading levels, learning styles, and student needs.",
    icon: "🎯",
    sortOrder: 9,
  },
  {
    name: "Administration & Productivity",
    slug: "administration",
    description: "Save time on admin tasks: emails, reports, communication, and organization.",
    icon: "⚡",
    sortOrder: 10,
  },
]

// 50+ AI Tools for Teachers with affiliate links and complete data
const tools = [
  // === LESSON PLANNING ===
  {
    name: "MagicSchool.ai",
    slug: "magicschool-ai",
    tagline: "The #1 AI platform for educators — lesson plans, assessments, rubrics, and more.",
    description: "MagicSchool.ai is the most widely used AI platform built specifically for teachers. It offers 60+ tools including lesson plan generator, rubric creator, text summarizer, multiple choice quiz maker, IEP generator, and more. Built by teachers for teachers with built-in safety and privacy controls.",
    logoUrl: "https://m.media-amazon.com/images/I/61xX1B6l7tL.png",
    websiteUrl: "https://www.magicschool.ai",
    affiliateUrl: "https://partnerstack.com/partners/magicschool",
    affiliateProgram: "PartnerStack",
    commissionRate: "20% recurring",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: true,
    rating: 4.8,
    reviewsCount: 1240,
    bestFor: ["Lesson Planning", "Assessment Creation", "Rubric Generation"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary", "Higher Ed"],
    curriculum: ["International", "KSSR", "KSSM", "IGCSE", "IB"],
    languages: ["English", "Spanish", "French"],
    categories: ["lesson-planning", "quiz-assessment", "grading-feedback", "differentiation"],
  },
  {
    name: "Eduaide.Ai",
    slug: "eduaide-ai",
    tagline: "AI-powered lesson planning with curriculum alignment and differentiation tools.",
    description: "Eduaide.Ai helps teachers create high-quality lessons, assessments, and resources with AI. It features curriculum-aligned lesson generation, differentiated instruction tools, and a rich library of teaching resources. Supports multiple languages and curriculum standards.",
    logoUrl: "https://eduaide.ai/favicon.ico",
    websiteUrl: "https://www.eduaide.ai",
    affiliateUrl: "https://eduaide.ai/affiliate",
    affiliateProgram: "Direct",
    commissionRate: "25% recurring",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: true,
    rating: 4.6,
    reviewsCount: 890,
    bestFor: ["Lesson Planning", "Differentiation", "Assessment"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary"],
    curriculum: ["International", "IB", "IGCSE"],
    languages: ["English", "Spanish"],
    categories: ["lesson-planning", "differentiation", "quiz-assessment"],
  },
  {
    name: "Curipod",
    slug: "curipod",
    tagline: "Interactive lesson creation with AI — polls, quizzes, word clouds, and more.",
    description: "Curipod turns any topic into an interactive lesson with AI-generated content, polls, word clouds, open-ended questions, and drawing tools. Students join with a code and participate in real-time. Great for engaging classrooms and checking understanding.",
    logoUrl: "https://curipod.com/favicon.ico",
    websiteUrl: "https://curipod.com",
    affiliateUrl: "https://partnerstack.com/partners/curipod",
    affiliateProgram: "PartnerStack",
    commissionRate: "20% recurring",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: true,
    rating: 4.7,
    reviewsCount: 2100,
    bestFor: ["Interactive Lessons", "Student Engagement", "Formative Assessment"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary"],
    curriculum: ["International", "IB", "IGCSE"],
    languages: ["English"],
    categories: ["lesson-planning", "presentations"],
  },
  {
    name: "LessonPlans.ai",
    slug: "lessonplans-ai",
    tagline: "Generate complete lesson plans in seconds with AI tailored to your grade and subject.",
    description: "LessonPlans.ai generates detailed, standards-aligned lesson plans in seconds. Just enter your grade level, subject, and topic — the AI creates a complete plan with learning objectives, activities, materials list, assessment ideas, and differentiation strategies.",
    logoUrl: "",
    websiteUrl: "https://www.lessonplans.ai",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Paid",
    startingPrice: "$9/mo",
    isFree: false,
    featured: false,
    rating: 4.4,
    reviewsCount: 450,
    bestFor: ["Lesson Planning", "Curriculum Planning"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary", "Higher Ed"],
    curriculum: ["International", "IB", "IGCSE"],
    languages: ["English"],
    categories: ["lesson-planning"],
  },
  {
    name: "Copilot Education",
    slug: "copilot-education",
    tagline: "AI-powered lesson and curriculum design tool for deeper learning.",
    description: "Copilot (formerly Copilot Education) is an AI-powered lesson and curriculum design tool that helps teachers create inquiry-based, deeper learning experiences. It focuses on project-based learning, essential questions, and authentic assessment design.",
    logoUrl: "",
    websiteUrl: "https://www.copilot.org",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Paid",
    startingPrice: "$24/yr",
    isFree: false,
    featured: false,
    rating: 4.5,
    reviewsCount: 670,
    bestFor: ["Curriculum Design", "Project-Based Learning", "Inquiry-Based Learning"],
    subjects: ["All Subjects"],
    gradeLevels: ["Secondary", "Higher Ed"],
    curriculum: ["International", "IB"],
    languages: ["English"],
    categories: ["lesson-planning"],
  },
  {
    name: "Karla (TeachFX)",
    slug: "karla-teachfx",
    tagline: "AI lesson planner that adapts to your teaching style and curriculum.",
    description: "Karla is an AI lesson planning assistant that learns your teaching style and curriculum preferences over time. It generates lessons that align with your specific standards, suggests activities based on student performance data, and helps you reflect on your teaching practice.",
    logoUrl: "",
    websiteUrl: "https://www.teachfx.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Paid",
    startingPrice: "$9.99/mo",
    isFree: false,
    featured: false,
    rating: 4.3,
    reviewsCount: 230,
    bestFor: ["Lesson Planning", "Teaching Reflection", "Instructional Coaching"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary"],
    curriculum: ["International", "CCSS"],
    languages: ["English"],
    categories: ["lesson-planning", "administration"],
  },

  // === QUIZ & ASSESSMENT ===
  {
    name: "Quizizz AI",
    slug: "quizizz-ai",
    tagline: "AI-powered quiz creation with gamification — students love it.",
    description: "Quizizz uses AI to generate quizzes, lessons, and assessments in seconds. Students answer at their own pace with fun memes and power-ups. Teachers get detailed reports on student performance. Features AI question generation from any text, PDF, or video.",
    logoUrl: "https://quizizz.com/favicon.ico",
    websiteUrl: "https://quizizz.com",
    affiliateUrl: "https://quizizz.com/teacher-referral",
    affiliateProgram: "Referral",
    commissionRate: "$10 per referral",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: true,
    rating: 4.8,
    reviewsCount: 5600,
    bestFor: ["Quiz Creation", "Gamified Assessment", "Formative Assessment"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary", "Higher Ed"],
    curriculum: ["International", "KSSR", "KSSM", "IGCSE", "IB"],
    languages: ["English", "Spanish", "Bahasa", "Mandarin"],
    categories: ["quiz-assessment", "content-creation"],
  },
  {
    name: "Twee",
    slug: "twee",
    tagline: "AI tools for English teachers — create exercises, texts, and questions instantly.",
    description: "Twee is an AI-powered platform specifically built for English language teachers. It generates reading comprehension texts, vocabulary exercises, grammar activities, discussion questions, fill-in-the-blank exercises, and more. Supports any level from beginner to advanced.",
    logoUrl: "https://twee.com/favicon.ico",
    websiteUrl: "https://twee.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.7,
    reviewsCount: 1800,
    bestFor: ["English Teaching", "Vocabulary", "Grammar Exercises"],
    subjects: ["English", "ESL", "EFL"],
    gradeLevels: ["Primary", "Secondary", "Higher Ed"],
    curriculum: ["International", "IGCSE", "IB"],
    languages: ["English", "Spanish", "French", "German"],
    categories: ["quiz-assessment", "content-creation", "language-learning"],
  },
  {
    name: "Conker",
    slug: "conker",
    tagline: "Create standards-aligned quizzes in minutes with AI.",
    description: "Conker lets teachers create multiple-choice and reading comprehension quizzes in seconds. Aligned to K-12 standards. Quizzes can be exported to Google Forms or played directly. Supports differentiated quizzes at different reading levels.",
    logoUrl: "",
    websiteUrl: "https://www.conker.ai",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.4,
    reviewsCount: 320,
    bestFor: ["Quiz Creation", "Standards-Aligned Assessment"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary"],
    curriculum: ["International", "CCSS", "TEKS"],
    languages: ["English", "Spanish"],
    categories: ["quiz-assessment"],
  },
  {
    name: "Formative AI",
    slug: "formative-ai",
    tagline: "Real-time formative assessment with AI-powered question generation.",
    description: "Formative is a real-time assessment platform. With Formative AI, teachers can instantly generate questions from any text or standard. Students answer in real-time, and teachers see live results to adjust instruction on the fly.",
    logoUrl: "",
    websiteUrl: "https://www.formative.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.5,
    reviewsCount: 1200,
    bestFor: ["Formative Assessment", "Real-Time Feedback"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary", "Higher Ed"],
    curriculum: ["International", "CCSS"],
    languages: ["English"],
    categories: ["quiz-assessment", "grading-feedback"],
  },

  // === GRADING & FEEDBACK ===
  {
    name: "Gradescope",
    slug: "gradescope",
    tagline: "AI-assisted grading for assignments, exams, and projects.",
    description: "Gradescope by Turnitin uses AI to speed up grading of paper-based exams, programming assignments, and bubble sheets. Teachers grade once and the AI applies the same rubric to all similar answers. Provides detailed analytics on student performance.",
    logoUrl: "",
    websiteUrl: "https://www.gradescope.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Paid",
    startingPrice: "Contact for pricing",
    isFree: false,
    featured: false,
    rating: 4.5,
    reviewsCount: 890,
    bestFor: ["Grading", "Rubric-Based Assessment", "Assignment Management"],
    subjects: ["All Subjects"],
    gradeLevels: ["Higher Ed", "Secondary"],
    curriculum: ["International", "IB"],
    languages: ["English"],
    categories: ["grading-feedback", "administration"],
  },
  {
    name: "AutoClassmate",
    slug: "autoclassmate",
    tagline: "AI tools for lesson planning, grading assistance, and classroom resources.",
    description: "AutoClassmate provides AI-powered assistance for lesson planning, grading support, classroom management resources, and student engagement activities. Includes a behavior reflection tool, icebreaker generator, and classroom newsletter creator.",
    logoUrl: "",
    websiteUrl: "https://www.autoclassmate.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Free",
    startingPrice: "Free",
    isFree: true,
    featured: false,
    rating: 4.2,
    reviewsCount: 150,
    bestFor: ["Lesson Planning", "Classroom Management", "Grading"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary"],
    curriculum: ["International"],
    languages: ["English"],
    categories: ["grading-feedback", "lesson-planning", "classroom-management"],
  },
  {
    name: "Grammar Check by AI",
    slug: "grammar-check-ai",
    tagline: "AI-powered grammar checking and writing feedback for student essays.",
    description: "Provides instant grammar checking, style suggestions, and writing feedback for student work. Teachers can set specific criteria and rubrics. Helps students improve their writing with detailed explanations.",
    logoUrl: "",
    websiteUrl: "https://www.grammarly.com/education",
    affiliateUrl: "https://grammarly.go2cloud.org/aff_c?offer_id=178&aff_id=0",
    affiliateProgram: "ShareASale",
    commissionRate: "25% recurring",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.7,
    reviewsCount: 15000,
    bestFor: ["Writing Feedback", "Grammar Checking", "Student Writing"],
    subjects: ["English", "Writing", "All Subjects"],
    gradeLevels: ["Primary", "Secondary", "Higher Ed"],
    curriculum: ["International", "IGCSE", "IB"],
    languages: ["English"],
    categories: ["grading-feedback", "content-creation"],
  },

  // === PRESENTATIONS ===
  {
    name: "Gamma.app",
    slug: "gamma-app",
    tagline: "Create beautiful presentations, documents, and webpages with AI.",
    description: "Gamma is an AI-powered presentation tool that generates stunning slides from a simple prompt. Teachers can create lesson presentations, study guides, and interactive content. Supports images, videos, and embedded content. Much faster than PowerPoint or Google Slides.",
    logoUrl: "https://gamma.app/favicon.ico",
    websiteUrl: "https://gamma.app",
    affiliateUrl: "https://gamma.app/affiliate-program",
    affiliateProgram: "Direct",
    commissionRate: "20% recurring",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: true,
    rating: 4.7,
    reviewsCount: 3200,
    bestFor: ["Presentations", "Visual Content", "Study Guides"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary", "Higher Ed"],
    curriculum: ["International", "IB", "IGCSE"],
    languages: ["English", "Spanish", "French", "German"],
    categories: ["presentations", "content-creation"],
  },
  {
    name: "SlidesAI",
    slug: "slidesai",
    tagline: "Turn any text into professional slides with AI — Google Slides add-on.",
    description: "SlidesAI is a Google Slides add-on that creates complete presentations from any text. Teachers can paste lesson notes, textbook chapters, or outlines — the AI generates well-designed slides instantly. Supports 100+ languages.",
    logoUrl: "",
    websiteUrl: "https://www.slidesai.io",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.4,
    reviewsCount: 580,
    bestFor: ["Google Slides", "Quick Presentations"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary", "Higher Ed"],
    curriculum: ["International"],
    languages: ["English", "Multiple Languages"],
    categories: ["presentations"],
  },
  {
    name: "Beautiful.ai",
    slug: "beautiful-ai",
    tagline: "AI-powered slide design that formats your content automatically.",
    description: "Beautiful.ai uses AI to design slides that look professionally crafted. Teachers just add content and the AI handles layout, spacing, and design. Perfect for creating polished lesson presentations without design skills.",
    logoUrl: "",
    websiteUrl: "https://www.beautiful.ai",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Paid",
    startingPrice: "$12/mo",
    isFree: false,
    featured: false,
    rating: 4.5,
    reviewsCount: 2100,
    bestFor: ["Professional Presentations", "Design Automation"],
    subjects: ["All Subjects"],
    gradeLevels: ["Higher Ed", "Secondary"],
    curriculum: ["International"],
    languages: ["English"],
    categories: ["presentations"],
  },
  {
    name: "Canva for Education",
    slug: "canva-education",
    tagline: "Free premium design tool for teachers and students — AI-powered creative suite.",
    description: "Canva for Education is FREE for K-12 teachers and students. Includes all premium features: Magic Design AI, Magic Write (AI text generator), Background Remover, video editing, and thousands of education templates. Teachers can create worksheets, presentations, posters, infographics, and more.",
    logoUrl: "https://static.canva.com/static/favicon.ico",
    websiteUrl: "https://www.canva.com/education",
    affiliateUrl: "https://www.canva.com/affiliates",
    affiliateProgram: "Canva Affiliates",
    commissionRate: "20% recurring",
    pricingTier: "Free",
    startingPrice: "Free (for education)",
    isFree: true,
    featured: true,
    rating: 4.9,
    reviewsCount: 25000,
    bestFor: ["Visual Content", "Worksheets", "Posters", "Presentations"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary", "Higher Ed"],
    curriculum: ["International", "KSSR", "KSSM", "IGCSE", "IB"],
    languages: ["English", "Bahasa", "Mandarin", "100+ languages"],
    categories: ["presentations", "content-creation", "video-multimedia"],
  },

  // === CONTENT CREATION ===
  {
    name: "Diffit",
    slug: "diffit",
    tagline: "Differentiate any text for any reading level in seconds.",
    description: "Diffit takes any text and instantly adapts it to different reading levels, languages, and learning needs. Teachers paste a URL, text, or upload a PDF — the AI creates versions at different Lexile levels with comprehension questions, vocabulary lists, and summaries.",
    logoUrl: "https://diffit.me/favicon.ico",
    websiteUrl: "https://diffit.me",
    affiliateUrl: "https://partnerstack.com/partners/diffit",
    affiliateProgram: "PartnerStack",
    commissionRate: "20% recurring",
    pricingTier: "Free",
    startingPrice: "Free",
    isFree: true,
    featured: true,
    rating: 4.8,
    reviewsCount: 950,
    bestFor: ["Differentiation", "Reading Comprehension", "ELL Support"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary"],
    curriculum: ["International", "CCSS", "IB"],
    languages: ["English", "Spanish", "French"],
    categories: ["content-creation", "differentiation", "language-learning"],
  },
  {
    name: "SchoolAI",
    slug: "schoolai",
    tagline: "All-in-one AI platform for schools with writing, reading, and tutoring tools.",
    description: "SchoolAI is a comprehensive AI platform for K-12 schools. It includes an AI writing assistant, reading comprehension tools, math tutoring, and personalized learning pathways. Teachers can monitor student AI usage and get analytics on learning progress. Built with student safety in mind.",
    logoUrl: "",
    websiteUrl: "https://www.schoolai.co",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Paid",
    startingPrice: "Contact for pricing",
    isFree: false,
    featured: true,
    rating: 4.6,
    reviewsCount: 780,
    bestFor: ["Writing Instruction", "Reading Support", "Tutoring"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary"],
    curriculum: ["International"],
    languages: ["English"],
    categories: ["content-creation", "differentiation"],
  },
  {
    name: "Khanmigo",
    slug: "khanmigo",
    tagline: "AI tutor from Khan Academy — guides students without giving answers.",
    description: "Khanmigo is Khan Academy's AI-powered tutoring assistant. Unlike ChatGPT, Khanmigo is designed to guide students to answers through Socratic questioning rather than giving direct answers. Covers math, science, humanities, and more. Teachers can access classroom monitoring features.",
    logoUrl: "https://www.khanacademy.org/favicon.ico",
    websiteUrl: "https://www.khanacademy.org/khan-labs",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Paid",
    startingPrice: "$44/yr",
    isFree: false,
    featured: true,
    rating: 4.6,
    reviewsCount: 4500,
    bestFor: ["Tutoring", "Homework Help", "Self-Paced Learning"],
    subjects: ["Math", "Science", "Humanities", "All Subjects"],
    gradeLevels: ["Primary", "Secondary"],
    curriculum: ["International", "CCSS", "IGCSE"],
    languages: ["English"],
    categories: ["content-creation", "differentiation"],
  },
  {
    name: "Worksheets.ai",
    slug: "worksheets-ai",
    tagline: "Generate custom worksheets with AI for any subject and grade level.",
    description: "Worksheets.ai creates printable worksheets, activity sheets, and practice problems in seconds. Teachers specify the subject, grade level, and topic — the AI generates ready-to-print worksheets with answer keys.",
    logoUrl: "",
    websiteUrl: "https://www.worksheets.ai",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.3,
    reviewsCount: 210,
    bestFor: ["Worksheet Creation", "Practice Problems", "Homework"],
    subjects: ["Math", "Science", "English"],
    gradeLevels: ["Primary", "Secondary"],
    curriculum: ["International"],
    languages: ["English"],
    categories: ["content-creation"],
  },
  {
    name: "Education Copilot",
    slug: "education-copilot",
    tagline: "AI lesson plans, handouts, and teaching resources in one click.",
    description: "Education Copilot generates lesson plans, student handouts, PowerPoint presentations, project outlines, and more. Teachers describe what they need and the AI creates professional-quality teaching materials instantly.",
    logoUrl: "",
    websiteUrl: "https://www.educationcopilot.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Paid",
    startingPrice: "$9/mo",
    isFree: false,
    featured: false,
    rating: 4.3,
    reviewsCount: 340,
    bestFor: ["Lesson Materials", "Handouts", "Projects"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary"],
    curriculum: ["International"],
    languages: ["English"],
    categories: ["content-creation", "lesson-planning"],
  },

  // === CLASSROOM MANAGEMENT ===
  {
    name: "ClassPoint",
    slug: "classpoint",
    tagline: "Interactive teaching directly inside PowerPoint with AI quiz generation.",
    description: "ClassPoint adds interactive teaching tools directly into Microsoft PowerPoint. Teachers can add live quizzes, polls, word clouds, and Q&A without leaving their slides. Includes AI-powered question generation from slide content. Students join via browser on any device.",
    logoUrl: "https://www.classpoint.io/favicon.ico",
    websiteUrl: "https://www.classpoint.io",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.7,
    reviewsCount: 2800,
    bestFor: ["Interactive PowerPoint", "Student Engagement", "Live Quizzes"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary", "Higher Ed"],
    curriculum: ["International"],
    languages: ["English"],
    categories: ["classroom-management", "presentations"],
  },
  {
    name: "Nearpod",
    slug: "nearpod",
    tagline: "Interactive lesson platform with VR, simulations, and real-time assessment.",
    description: "Nearpod is a student engagement platform with interactive lessons, video content, virtual reality field trips, gamified quizzes, and collaborative activities. Teachers control the pace and see student responses in real-time. Includes AI lesson creation.",
    logoUrl: "https://nearpod.com/favicon.ico",
    websiteUrl: "https://nearpod.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.6,
    reviewsCount: 8900,
    bestFor: ["Interactive Lessons", "VR Content", "Student Engagement"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary"],
    curriculum: ["International"],
    languages: ["English", "Spanish"],
    categories: ["classroom-management", "presentations"],
  },
  {
    name: "ClassDojo",
    slug: "classdojo",
    tagline: "Classroom community platform with behavior tracking and parent communication.",
    description: "ClassDojo connects teachers, students, and families. Teachers can share photos, videos, and announcements. Students build portfolios. Includes behavior tracking with positive reinforcement. AI features help with messaging translation and communication.",
    logoUrl: "https://www.classdojo.com/favicon.ico",
    websiteUrl: "https://www.classdojo.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Free",
    startingPrice: "Free",
    isFree: true,
    featured: false,
    rating: 4.5,
    reviewsCount: 12000,
    bestFor: ["Behavior Management", "Parent Communication", "Classroom Community"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary"],
    curriculum: ["International"],
    languages: ["English", "Spanish", "Mandarin", "35+ languages"],
    categories: ["classroom-management"],
  },
  {
    name: "Socrative",
    slug: "socrative",
    tagline: "Real-time student response system with AI-generated questions.",
    description: "Socrative is a student response system that lets teachers create quizzes, polls, exit tickets, and space races. Students respond on any device. AI features help generate questions from content. Instant reports show class understanding.",
    logoUrl: "",
    websiteUrl: "https://www.socrative.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.4,
    reviewsCount: 3400,
    bestFor: ["Student Response", "Exit Tickets", "Quick Checks"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary", "Higher Ed"],
    curriculum: ["International"],
    languages: ["English"],
    categories: ["classroom-management", "quiz-assessment"],
  },
  {
    name: "GoGuardian",
    slug: "goguardian",
    tagline: "Student safety and classroom management for school devices.",
    description: "GoGuardian helps schools manage student devices with classroom management, content filtering, and student safety monitoring. Teachers can see student screens, block distracting sites, and launch focused learning sessions. AI features detect at-risk behaviors.",
    logoUrl: "",
    websiteUrl: "https://www.goguardian.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Paid",
    startingPrice: "Contact for pricing",
    isFree: false,
    featured: false,
    rating: 4.3,
    reviewsCount: 2100,
    bestFor: ["Device Management", "Student Safety", "Screen Monitoring"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary"],
    curriculum: ["International"],
    languages: ["English"],
    categories: ["classroom-management"],
  },

  // === VIDEO & MULTIMEDIA ===
  {
    name: "Synthesia",
    slug: "synthesia",
    tagline: "Create AI video lessons with virtual presenters in 120+ languages.",
    description: "Synthesia lets teachers create professional video lessons using AI avatars. Type your script and choose an avatar — the AI generates a video that looks like a real person speaking. Supports 120+ languages and accents. No camera, microphone, or studio needed.",
    logoUrl: "https://www.synthesia.io/favicon.ico",
    websiteUrl: "https://www.synthesia.io",
    affiliateUrl: "https://www.synthesia.io/affiliates",
    affiliateProgram: "Direct",
    commissionRate: "20% recurring",
    pricingTier: "Paid",
    startingPrice: "$29/mo",
    isFree: false,
    featured: false,
    rating: 4.6,
    reviewsCount: 1800,
    bestFor: ["Video Lessons", "Explainer Videos", "Language Learning"],
    subjects: ["All Subjects"],
    gradeLevels: ["Secondary", "Higher Ed"],
    curriculum: ["International"],
    languages: ["English", "120+ languages"],
    categories: ["video-multimedia", "content-creation"],
  },
  {
    name: "Pictory",
    slug: "pictory",
    tagline: "Turn text or articles into engaging educational videos with AI.",
    description: "Pictory converts blog posts, articles, or lesson notes into engaging videos with stock footage, music, and voiceover. Teachers can create video summaries, lesson introductions, and revision content without any video editing skills.",
    logoUrl: "",
    websiteUrl: "https://pictory.ai",
    affiliateUrl: "https://pictory.ai/affiliate-program",
    affiliateProgram: "Direct",
    commissionRate: "25% recurring",
    pricingTier: "Paid",
    startingPrice: "$19/mo",
    isFree: false,
    featured: false,
    rating: 4.5,
    reviewsCount: 670,
    bestFor: ["Video Creation", "Content Repurposing", "Lesson Videos"],
    subjects: ["All Subjects"],
    gradeLevels: ["Secondary", "Higher Ed"],
    curriculum: ["International"],
    languages: ["English"],
    categories: ["video-multimedia", "content-creation"],
  },
  {
    name: "Animaker",
    slug: "animaker",
    tagline: "Animated video creation for classrooms — no animation experience needed.",
    description: "Animaker is a DIY animation tool for creating educational animated videos. Teachers can create animated explainer videos, whiteboard animations, and infographic videos. Includes education-specific templates and characters.",
    logoUrl: "",
    websiteUrl: "https://www.animaker.com",
    affiliateUrl: "https://www.animaker.com/affiliate",
    affiliateProgram: "Direct",
    commissionRate: "25% recurring",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.4,
    reviewsCount: 1500,
    bestFor: ["Animated Videos", "Explainer Content", "Student Projects"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary"],
    curriculum: ["International"],
    languages: ["English"],
    categories: ["video-multimedia"],
  },
  {
    name: "ScreenPal",
    slug: "screenpal",
    tagline: "Screen recording and video editing for flipped classroom content.",
    description: "ScreenPal (formerly Screencast-O-Matic) is a screen recording and video editing tool popular with educators. Teachers create flipped classroom videos, tutorials, and recorded lessons. Includes AI-powered captioning, editing, and quiz embedded in videos.",
    logoUrl: "",
    websiteUrl: "https://screenpal.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.3,
    reviewsCount: 2800,
    bestFor: ["Screen Recording", "Flipped Classroom", "Tutorial Videos"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary", "Higher Ed"],
    curriculum: ["International"],
    languages: ["English"],
    categories: ["video-multimedia"],
  },

  // === LANGUAGE LEARNING ===
  {
    name: "Duolingo for Schools",
    slug: "duolingo-schools",
    tagline: "Free AI-powered language learning platform with teacher dashboard.",
    description: "Duolingo for Schools gives teachers free access to Duolingo's full language learning platform with a teacher dashboard to track student progress. AI adapts lessons to each student's level. Supports 40+ languages. Completely free with no ads.",
    logoUrl: "https://www.duolingo.com/favicon.ico",
    websiteUrl: "https://schools.duolingo.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Free",
    startingPrice: "Free",
    isFree: true,
    featured: false,
    rating: 4.7,
    reviewsCount: 18000,
    bestFor: ["Language Learning", "Self-Paced Practice", "Supplemental Learning"],
    subjects: ["Languages"],
    gradeLevels: ["Primary", "Secondary", "Higher Ed"],
    curriculum: ["International"],
    languages: ["English", "Spanish", "French", "German", "40+ languages"],
    categories: ["language-learning"],
  },
  {
    name: "Lingostar",
    slug: "lingostar",
    tagline: "AI language tutor that students can practice speaking with anytime.",
    description: "Lingostar is an AI language speaking tutor that students can practice with anytime. It provides real-time conversation practice with pronunciation feedback. Teachers can assign topics aligned with their curriculum.",
    logoUrl: "",
    websiteUrl: "https://www.lingostar.ai",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.2,
    reviewsCount: 180,
    bestFor: ["Speaking Practice", "Pronunciation", "Conversation Skills"],
    subjects: ["Languages"],
    gradeLevels: ["Secondary", "Higher Ed"],
    curriculum: ["International"],
    languages: ["English", "Spanish", "French"],
    categories: ["language-learning"],
  },
  {
    name: "ReadSpeaker",
    slug: "readspeaker",
    tagline: "AI text-to-speech for educational materials supporting comprehension.",
    description: "ReadSpeaker provides lifelike AI text-to-speech for educational materials. Students can listen to any text content, improving reading comprehension and accessibility. Supports multiple languages and voices. Integrates with learning management systems.",
    logoUrl: "",
    websiteUrl: "https://www.readspeaker.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Paid",
    startingPrice: "Contact for pricing",
    isFree: false,
    featured: false,
    rating: 4.3,
    reviewsCount: 450,
    bestFor: ["Text-to-Speech", "Accessibility", "Reading Support"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary", "Higher Ed"],
    curriculum: ["International"],
    languages: ["English", "30+ languages"],
    categories: ["language-learning", "differentiation"],
  },

  // === DIFFERENTIATION & PERSONALIZATION ===
  {
    name: "Newsela",
    slug: "newsela",
    tagline: "Adaptive reading content at 5 different Lexile levels with AI.",
    description: "Newsela takes news articles and adapts them to 5 different reading levels. Teachers can assign the same content to the whole class — each student reads at their own level. Includes AI-powered comprehension quizzes and writing prompts. Covers ELA, science, social studies, and SEL.",
    logoUrl: "",
    websiteUrl: "https://newsela.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.6,
    reviewsCount: 6700,
    bestFor: ["Differentiated Reading", "Content Adaptation", "Literacy"],
    subjects: ["ELA", "Science", "Social Studies"],
    gradeLevels: ["Primary", "Secondary"],
    curriculum: ["International", "CCSS"],
    languages: ["English", "Spanish"],
    categories: ["differentiation", "content-creation"],
  },
  {
    name: "DreamBox Learning",
    slug: "dreambox-learning",
    tagline: "AI-powered adaptive math program that personalizes to each student.",
    description: "DreamBox Learning is an adaptive K-8 math program that uses AI to personalize instruction for every student. It adjusts difficulty, pacing, and content in real-time based on how students solve problems. Teachers get detailed reports on student progress and gaps.",
    logoUrl: "",
    websiteUrl: "https://www.dreambox.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Paid",
    startingPrice: "Contact for pricing",
    isFree: false,
    featured: false,
    rating: 4.5,
    reviewsCount: 3200,
    bestFor: ["Adaptive Math", "Personalized Learning", "Math Intervention"],
    subjects: ["Math"],
    gradeLevels: ["Primary"],
    curriculum: ["International", "CCSS"],
    languages: ["English", "Spanish"],
    categories: ["differentiation"],
  },
  {
    name: "Knewton",
    slug: "knewton",
    tagline: "Adaptive learning platform that personalizes course content for each student.",
    description: "Knewton's adaptive learning platform uses AI to create personalized learning paths for each student. It analyzes performance data to identify gaps and deliver targeted content. Used by major educational publishers and institutions.",
    logoUrl: "",
    websiteUrl: "https://www.knewton.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Paid",
    startingPrice: "Contact for pricing",
    isFree: false,
    featured: false,
    rating: 4.2,
    reviewsCount: 890,
    bestFor: ["Adaptive Learning", "Higher Ed Courseware", "Personalization"],
    subjects: ["All Subjects"],
    gradeLevels: ["Higher Ed", "Secondary"],
    curriculum: ["International"],
    languages: ["English"],
    categories: ["differentiation"],
  },
  {
    name: "Read&Write by Texthelp",
    slug: "readwrite-texthelp",
    tagline: "AI literacy support tool for reading, writing, and comprehension.",
    description: "Read&Write is a literacy support tool that helps students with reading, writing, and comprehension. Features include text-to-speech, word prediction, talking dictionary, picture dictionaries, voice typing, and text summarization. Built for students with learning differences like dyslexia.",
    logoUrl: "",
    websiteUrl: "https://www.texthelp.com/products/read-write",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Paid",
    startingPrice: "$6.95/yr (education)",
    isFree: false,
    featured: false,
    rating: 4.5,
    reviewsCount: 3400,
    bestFor: ["Literacy Support", "Special Education", "Accessibility"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary", "Higher Ed"],
    curriculum: ["International"],
    languages: ["English"],
    categories: ["differentiation", "content-creation"],
  },

  // === ADMINISTRATION & PRODUCTIVITY ===
  {
    name: "ChatGPT",
    slug: "chatgpt",
    tagline: "General AI assistant for teachers — lesson ideas, emails, reports, and more.",
    description: "ChatGPT can help teachers with a wide range of administrative tasks: writing emails to parents, creating newsletter content, drafting report card comments, generating discussion prompts, planning lessons, and creating rubrics. The paid version (ChatGPT Plus) includes GPT-4 access, image generation, and file uploads.",
    logoUrl: "https://openai.com/favicon.ico",
    websiteUrl: "https://chat.openai.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: true,
    rating: 4.8,
    reviewsCount: 50000,
    bestFor: ["Administrative Tasks", "Content Ideas", "Drafting", "Planning"],
    subjects: ["All Subjects"],
    gradeLevels: ["All Levels"],
    curriculum: ["International"],
    languages: ["English", "50+ languages"],
    categories: ["administration", "content-creation", "lesson-planning"],
  },
  {
    name: "Claude AI",
    slug: "claude-ai",
    tagline: "AI assistant with long context — great for grading essays and analyzing student work.",
    description: "Claude by Anthropic is excellent for teachers because of its large context window (200K tokens). It can analyze lengthy student essays, grade them against rubrics, provide detailed feedback, and help with curriculum planning. Also great for creating detailed lesson plans and unit outlines.",
    logoUrl: "https://claude.ai/favicon.ico",
    websiteUrl: "https://claude.ai",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.7,
    reviewsCount: 12000,
    bestFor: ["Essay Grading", "Long-Form Analysis", "Curriculum Planning"],
    subjects: ["All Subjects"],
    gradeLevels: ["Secondary", "Higher Ed"],
    curriculum: ["International"],
    languages: ["English", "Multiple Languages"],
    categories: ["administration", "grading-feedback"],
  },
  {
    name: "Google Gemini",
    slug: "google-gemini",
    tagline: "Google's AI assistant integrated with Google Workspace for Education.",
    description: "Gemini integrates with Google Workspace for Education — teachers can use it within Google Docs, Sheets, Gmail, and Slides. Helps draft lesson plans in Docs, create slides in Slides, write emails in Gmail, and analyze data in Sheets. Includes safety features for education.",
    logoUrl: "https://gemini.google.com/favicon.ico",
    websiteUrl: "https://gemini.google.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.6,
    reviewsCount: 8000,
    bestFor: ["Google Workspace Integration", "Administrative Tasks"],
    subjects: ["All Subjects"],
    gradeLevels: ["All Levels"],
    curriculum: ["International"],
    languages: ["English", "40+ languages"],
    categories: ["administration", "content-creation"],
  },
  {
    name: "Microsoft Copilot",
    slug: "microsoft-copilot",
    tagline: "AI assistant built into Microsoft 365 for Education.",
    description: "Microsoft Copilot integrates with Word, PowerPoint, Excel, and Teams for Education. Teachers can create lesson plans in Word, generate slide decks in PowerPoint, analyze grade data in Excel, and automate Teams communications. Free with Microsoft 365 for Education accounts.",
    logoUrl: "",
    websiteUrl: "https://copilot.microsoft.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Free",
    startingPrice: "Free (with M365 Education)",
    isFree: true,
    featured: false,
    rating: 4.5,
    reviewsCount: 5600,
    bestFor: ["Microsoft 365 Integration", "Document Creation"],
    subjects: ["All Subjects"],
    gradeLevels: ["All Levels"],
    curriculum: ["International"],
    languages: ["English", "Multiple Languages"],
    categories: ["administration", "presentations", "content-creation"],
  },
  {
    name: "Notion AI",
    slug: "notion-ai",
    tagline: "AI-powered workspace for lesson planning, curriculum mapping, and collaboration.",
    description: "Notion AI combines note-taking, databases, wikis, and AI in one workspace. Teachers can create curriculum maps, lesson databases, collaborative planning documents, and department wikis. AI features help generate content, summarize notes, and brainstorm ideas.",
    logoUrl: "https://www.notion.so/favicon.ico",
    websiteUrl: "https://www.notion.so",
    affiliateUrl: "https://www.notion.so/referral",
    affiliateProgram: "Referral",
    commissionRate: "$10/referral",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.6,
    reviewsCount: 15000,
    bestFor: ["Organization", "Curriculum Mapping", "Collaborative Planning"],
    subjects: ["All Subjects"],
    gradeLevels: ["All Levels"],
    curriculum: ["International"],
    languages: ["English", "Multiple Languages"],
    categories: ["administration", "lesson-planning"],
  },
  {
    name: "Mailbutler",
    slug: "mailbutler",
    tagline: "AI email assistant for teachers — schedule, track, and automate parent communication.",
    description: "Mailbutler integrates with Gmail and Outlook to help teachers manage email communication with parents, colleagues, and administrators. Features include email scheduling, tracking, templates, and AI-powered reply suggestions. Saves hours of email management time.",
    logoUrl: "",
    websiteUrl: "https://www.mailbutler.io",
    affiliateUrl: "https://www.mailbutler.io/affiliates",
    affiliateProgram: "Direct",
    commissionRate: "30% recurring",
    pricingTier: "Paid",
    startingPrice: "$4.95/mo",
    isFree: false,
    featured: false,
    rating: 4.3,
    reviewsCount: 450,
    bestFor: ["Email Management", "Parent Communication", "Productivity"],
    subjects: ["All Subjects"],
    gradeLevels: ["All Levels"],
    curriculum: ["International"],
    languages: ["English"],
    categories: ["administration"],
  },
  {
    name: "Otter.ai",
    slug: "otter-ai",
    tagline: "AI meeting transcription and notes — great for parent-teacher meetings and PD.",
    description: "Otter.ai records and transcribes meetings in real-time. Teachers can use it for parent-teacher conferences, department meetings, professional development sessions, and IEP meetings. Automatically generates summaries and action items. Searchable transcripts.",
    logoUrl: "https://otter.ai/favicon.ico",
    websiteUrl: "https://otter.ai",
    affiliateUrl: "https://otter.ai/referral",
    affiliateProgram: "Referral",
    commissionRate: "1 month free/referral",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.5,
    reviewsCount: 5600,
    bestFor: ["Transcription", "Meeting Notes", "Professional Development"],
    subjects: ["All Subjects"],
    gradeLevels: ["All Levels"],
    curriculum: ["International"],
    languages: ["English"],
    categories: ["administration"],
  },

  // === MORE TOOLS ===
  {
    name: "Quizlet",
    slug: "quizlet",
    tagline: "AI-powered flashcards, study sets, and learning games for students.",
    description: "Quizlet is the world's most popular flashcard platform. With AI features, teachers can generate flashcard sets, practice tests, and study games from any content. Students can study with Learn mode, Test mode, Match games, and Gravity. New AI features include Q-Chat (AI tutor) and Magic Notes.",
    logoUrl: "https://quizlet.com/favicon.ico",
    websiteUrl: "https://quizlet.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.7,
    reviewsCount: 25000,
    bestFor: ["Flashcards", "Study Tools", "Vocabulary Practice"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary", "Higher Ed"],
    curriculum: ["International", "KSSR", "KSSM", "IGCSE", "IB"],
    languages: ["English", "Multiple Languages"],
    categories: ["quiz-assessment", "content-creation", "language-learning"],
  },
  {
    name: "Padlet",
    slug: "padlet",
    tagline: "Collaborative digital bulletin board for student brainstorming and sharing.",
    description: "Padlet is a collaborative digital canvas where students can post text, images, videos, and links. AI features help generate prompts, grade posts, and create templates. Great for brainstorming, KWL charts, exit tickets, and collaborative projects.",
    logoUrl: "https://padlet.com/favicon.ico",
    websiteUrl: "https://padlet.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.6,
    reviewsCount: 8900,
    bestFor: ["Collaboration", "Brainstorming", "Student Sharing"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary", "Higher Ed"],
    curriculum: ["International"],
    languages: ["English", "Multiple Languages"],
    categories: ["classroom-management", "content-creation"],
  },
  {
    name: "Fliki",
    slug: "fliki",
    tagline: "Turn text into videos with AI voiceovers — perfect for lesson content.",
    description: "Fliki converts text to videos with realistic AI voiceovers. Teachers can create narrated presentations, explainer videos, and listening comprehension content. Supports 80+ languages with natural-sounding voices. Includes stock video and image library.",
    logoUrl: "",
    websiteUrl: "https://fliki.ai",
    affiliateUrl: "https://fliki.ai/affiliates",
    affiliateProgram: "Direct",
    commissionRate: "30% recurring",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.5,
    reviewsCount: 1200,
    bestFor: ["Text-to-Video", "Voiceovers", "Content Creation"],
    subjects: ["All Subjects"],
    gradeLevels: ["All Levels"],
    curriculum: ["International"],
    languages: ["English", "80+ languages"],
    categories: ["video-multimedia", "content-creation"],
  },
  {
    name: "Lumen5",
    slug: "lumen5",
    tagline: "AI video maker for educational content and lesson summaries.",
    description: "Lumen5 transforms text content into engaging videos with AI. Teachers paste lesson notes, articles, or textbook chapters — the AI creates a video with matching visuals, music, and voiceover. Ideal for creating short lesson summaries and revision videos.",
    logoUrl: "",
    websiteUrl: "https://lumen5.com",
    affiliateUrl: "https://lumen5.com/affiliate-program",
    affiliateProgram: "Direct",
    commissionRate: "20% recurring",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.4,
    reviewsCount: 3400,
    bestFor: ["Video Creation", "Lesson Summaries", "Social Media Content"],
    subjects: ["All Subjects"],
    gradeLevels: ["Secondary", "Higher Ed"],
    curriculum: ["International"],
    languages: ["English"],
    categories: ["video-multimedia", "content-creation"],
  },
  {
    name: "Brisk Teaching",
    slug: "brisk-teaching",
    tagline: "Free AI Chrome extension for lesson planning, feedback, and content creation.",
    description: "Brisk Teaching is a free Chrome extension that works across websites. Teachers can generate lesson plans from any webpage, give AI-powered feedback on student writing, create presentations, adjust reading levels, and more. Built specifically for educators with privacy in mind.",
    logoUrl: "",
    websiteUrl: "https://www.briskteaching.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Free",
    startingPrice: "Free",
    isFree: true,
    featured: false,
    rating: 4.7,
    reviewsCount: 2300,
    bestFor: ["Lesson Planning", "Feedback", "Chrome Extension"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary"],
    curriculum: ["International"],
    languages: ["English"],
    categories: ["lesson-planning", "grading-feedback", "content-creation"],
  },
  {
    name: "Almanack",
    slug: "almanack",
    tagline: "AI platform for teachers — lesson plans, worksheets, assessments, and more.",
    description: "Almanack is an all-in-one AI teaching platform that generates lesson plans, worksheets, assessments, report card comments, and unit plans. Gets regular updates with new tools based on teacher feedback. Supports Ontario, British Columbia, and other Canadian curricula.",
    logoUrl: "",
    websiteUrl: "https://almanack.ai",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Paid",
    startingPrice: "$9/mo",
    isFree: false,
    featured: false,
    rating: 4.4,
    reviewsCount: 560,
    bestFor: ["Lesson Planning", "Worksheets", "Assessments"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary"],
    curriculum: ["International", "Canadian"],
    languages: ["English", "French"],
    categories: ["lesson-planning", "content-creation", "quiz-assessment"],
  },
  {
    name: "Mindgrasp",
    slug: "mindgrasp",
    tagline: "Turn any video, PDF, or audio into notes, quizzes, and flashcards with AI.",
    description: "Mindgrasp automatically generates notes, summaries, flashcards, and quizzes from uploaded content — videos, PDFs, audio recordings, and URLs. Teachers can create study materials from YouTube videos, lecture recordings, or textbook PDFs in minutes.",
    logoUrl: "",
    websiteUrl: "https://www.mindgrasp.ai",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Paid",
    startingPrice: "$8.99/mo",
    isFree: false,
    featured: false,
    rating: 4.3,
    reviewsCount: 340,
    bestFor: ["Content Summarization", "Note Taking", "Study Materials"],
    subjects: ["All Subjects"],
    gradeLevels: ["Higher Ed", "Secondary"],
    curriculum: ["International"],
    languages: ["English"],
    categories: ["content-creation", "quiz-assessment"],
  },
  {
    name: "Yippity",
    slug: "yippity",
    tagline: "Turn any text or website into interactive quizzes with AI.",
    description: "Yippity generates quiz questions from any text, URL, or uploaded document. Teachers paste lesson content — the AI creates multiple-choice, true/false, and fill-in-the-blank questions. Quizzes can be exported or shared with a link.",
    logoUrl: "",
    websiteUrl: "https://yippity.io",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.2,
    reviewsCount: 200,
    bestFor: ["Quiz Generation", "Quick Assessment"],
    subjects: ["All Subjects"],
    gradeLevels: ["Secondary", "Higher Ed"],
    curriculum: ["International"],
    languages: ["English"],
    categories: ["quiz-assessment"],
  },
  {
    name: "TeachMateAI",
    slug: "teachmate-ai",
    tagline: "AI tools for UK teachers — lesson plans, reports, and resources.",
    description: "TeachMateAI is built specifically for UK teachers with curriculum alignment to the National Curriculum for England. Includes lesson plan generator, report writer, reading comprehension creator, model text generator, and knowledge organiser creator.",
    logoUrl: "",
    websiteUrl: "https://www.teachmateai.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Paid",
    startingPrice: "£9.99/mo",
    isFree: false,
    featured: false,
    rating: 4.5,
    reviewsCount: 780,
    bestFor: ["UK Curriculum", "Report Writing", "Lesson Planning"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary"],
    curriculum: ["UK National Curriculum"],
    languages: ["English"],
    categories: ["lesson-planning", "content-creation", "administration"],
  },
  {
    name: "To Teach AI",
    slug: "to-teach-ai",
    tagline: "Create personalized learning materials for your students with AI.",
    description: "To Teach AI generates personalized exercises, worksheets, and lesson materials based on each student's level and interests. Teachers can create differentiated content for different learning levels within the same class. Supports multiple languages and subjects.",
    logoUrl: "",
    websiteUrl: "https://www.toteach.ai",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.4,
    reviewsCount: 420,
    bestFor: ["Personalized Materials", "Differentiation", "Worksheet Creation"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary"],
    curriculum: ["International"],
    languages: ["English", "German", "French", "Spanish"],
    categories: ["differentiation", "content-creation"],
  },
  {
    name: "Caktus AI",
    slug: "caktus-ai",
    tagline: "AI study assistant for students with writing, math, and coding help.",
    description: "Caktus AI is an AI study assistant designed for students. It helps with essay writing, math problem-solving, coding, and test preparation. Teachers can monitor usage and see what students are working on. Includes plagiarism detection and citation generation.",
    logoUrl: "",
    websiteUrl: "https://www.caktus.ai",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Paid",
    startingPrice: "$9.99/mo",
    isFree: false,
    featured: false,
    rating: 4.3,
    reviewsCount: 560,
    bestFor: ["Student Study Help", "Writing Assistance", "STEM Support"],
    subjects: ["All Subjects"],
    gradeLevels: ["Secondary", "Higher Ed"],
    curriculum: ["International"],
    languages: ["English"],
    categories: ["differentiation", "content-creation"],
  },
  {
    name: "Gimkit",
    slug: "gimkit",
    tagline: "Game-based learning platform where students earn virtual currency.",
    description: "Gimkit is a game-based learning platform where students answer questions to earn in-game currency they can use for power-ups and upgrades. AI features help generate question sets from any content. Students find it highly engaging because of the game mechanics.",
    logoUrl: "",
    websiteUrl: "https://www.gimkit.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.6,
    reviewsCount: 4500,
    bestFor: ["Gamified Learning", "Review Games", "Student Engagement"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary"],
    curriculum: ["International"],
    languages: ["English"],
    categories: ["quiz-assessment", "classroom-management"],
  },
  {
    name: "Bloombot",
    slug: "bloombot",
    tagline: "AI quiz generator that aligns questions to Bloom's Taxonomy levels.",
    description: "Bloombot creates quiz questions aligned to different levels of Bloom's Taxonomy — from basic recall to higher-order thinking. Teachers can specify the taxonomy level and get questions that target analysis, evaluation, and creation skills. Saves hours of question design time.",
    logoUrl: "",
    websiteUrl: "https://www.bloombot.ai",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.1,
    reviewsCount: 120,
    bestFor: ["Higher-Order Thinking", "Critical Thinking", "Assessment Design"],
    subjects: ["All Subjects"],
    gradeLevels: ["Secondary", "Higher Ed"],
    curriculum: ["International", "IB"],
    languages: ["English"],
    categories: ["quiz-assessment"],
  },
  {
    name: "Parlay",
    slug: "parlay",
    tagline: "AI-powered discussion platform for meaningful classroom conversations.",
    description: "Parlay facilitates meaningful classroom discussions with AI-generated prompts, real-time moderation, and analytics on student participation. Teachers can assess discussion quality and identify students who need more encouragement. Great for Socratic seminars and debates.",
    logoUrl: "",
    websiteUrl: "https://www.parlayideas.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Paid",
    startingPrice: "Contact for pricing",
    isFree: false,
    featured: false,
    rating: 4.5,
    reviewsCount: 340,
    bestFor: ["Class Discussion", "Socratic Seminar", "Student Voice"],
    subjects: ["ELA", "Social Studies", "All Subjects"],
    gradeLevels: ["Secondary", "Higher Ed"],
    curriculum: ["International"],
    languages: ["English"],
    categories: ["classroom-management", "content-creation"],
  },
  {
    name: "SplashLearn",
    slug: "splashlearn",
    tagline: "AI-powered math and reading program for K-5 with adaptive learning paths.",
    description: "SplashLearn is an adaptive learning program for K-5 math and reading. AI personalizes each child's learning path based on their performance. Teachers get detailed reports on student progress, skill gaps, and growth. Over 40 million students use it worldwide.",
    logoUrl: "",
    websiteUrl: "https://www.splashlearn.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Paid",
    startingPrice: "$7.99/mo",
    isFree: false,
    featured: false,
    rating: 4.5,
    reviewsCount: 8900,
    bestFor: ["Early Math", "Reading Skills", "Adaptive Learning"],
    subjects: ["Math", "Reading"],
    gradeLevels: ["Primary"],
    curriculum: ["International", "CCSS"],
    languages: ["English"],
    categories: ["differentiation", "content-creation"],
  },
  {
    name: "Storybird",
    slug: "storybird",
    tagline: "AI-powered storytelling platform for creative writing in classrooms.",
    description: "Storybird uses AI to help students create beautiful stories, poems, and comics. Teachers can assign creative writing projects and the AI helps students with plot development, character creation, and illustration. Includes curriculum-aligned writing prompts and assessment tools.",
    logoUrl: "",
    websiteUrl: "https://storybird.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Paid",
    startingPrice: "Contact for pricing",
    isFree: false,
    featured: false,
    rating: 4.4,
    reviewsCount: 2100,
    bestFor: ["Creative Writing", "Storytelling", "Literacy"],
    subjects: ["ELA", "English"],
    gradeLevels: ["Primary", "Secondary"],
    curriculum: ["International"],
    languages: ["English"],
    categories: ["content-creation", "language-learning"],
  },
  {
    name: "QuestionWell",
    slug: "questionwell",
    tagline: "Generate unlimited standards-aligned questions from any text with AI.",
    description: "QuestionWell generates unlimited questions from any text, video, or topic. Teachers paste content or upload a file — the AI creates multiple-choice, short answer, and open-ended questions aligned to learning standards. Questions can be exported to Google Forms, Kahoot, Quizizz, and more.",
    logoUrl: "",
    websiteUrl: "https://www.questionwell.org",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Free",
    startingPrice: "Free",
    isFree: true,
    featured: false,
    rating: 4.4,
    reviewsCount: 310,
    bestFor: ["Question Generation", "Standards Alignment", "Assessment Creation"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary"],
    curriculum: ["International", "CCSS"],
    languages: ["English"],
    categories: ["quiz-assessment"],
  },
  {
    name: "Writable",
    slug: "writable",
    tagline: "AI-powered writing practice with instant feedback for students.",
    description: "Writable is a writing instruction platform that uses AI to give students instant feedback on their writing. Teachers can assign writing prompts, and the AI provides feedback on grammar, organization, evidence use, and style. Includes plagiarism checking and peer review features.",
    logoUrl: "",
    websiteUrl: "https://www.writable.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Paid",
    startingPrice: "Contact for pricing",
    isFree: false,
    featured: false,
    rating: 4.5,
    reviewsCount: 670,
    bestFor: ["Writing Instruction", "Writing Feedback", "Essay Practice"],
    subjects: ["ELA", "English", "All Subjects"],
    gradeLevels: ["Secondary", "Higher Ed"],
    curriculum: ["International"],
    languages: ["English"],
    categories: ["grading-feedback", "content-creation"],
  },
  {
    name: "Perplexity AI",
    slug: "perplexity-ai",
    tagline: "AI research assistant with citations — great for student research projects.",
    description: "Perplexity AI is an AI-powered search engine that provides answers with citations. Students can use it for research, fact-checking, and exploring topics. Teachers can create Collections for specific research topics. The Pro version includes file uploads and longer context.",
    logoUrl: "https://perplexity.ai/favicon.ico",
    websiteUrl: "https://www.perplexity.ai",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.7,
    reviewsCount: 15000,
    bestFor: ["Student Research", "Fact-Checking", "Inquiry-Based Learning"],
    subjects: ["All Subjects"],
    gradeLevels: ["Secondary", "Higher Ed"],
    curriculum: ["International"],
    languages: ["English", "Multiple Languages"],
    categories: ["administration", "content-creation"],
  },
  {
    name: "Ludia",
    slug: "ludia",
    tagline: "Turn any lesson into a gamified adventure with AI-generated storylines.",
    description: "Ludia turns any curriculum content into an interactive story-based game. Teachers input the lesson content — the AI generates a storyline, challenges, and rewards. Students progress through the story by answering questions correctly. Makes any subject more engaging.",
    logoUrl: "",
    websiteUrl: "https://www.ludia.ai",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Paid",
    startingPrice: "Contact for pricing",
    isFree: false,
    featured: false,
    rating: 4.3,
    reviewsCount: 180,
    bestFor: ["Gamification", "Student Engagement", "Interactive Learning"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary", "Secondary"],
    curriculum: ["International"],
    languages: ["English"],
    categories: ["classroom-management", "content-creation"],
  },
  {
    name: "TinyTap",
    slug: "tinytap",
    tagline: "Create interactive educational games and activities with AI.",
    description: "TinyTap lets teachers create interactive educational games, lessons, and activities without coding. AI features help generate content from any topic. Students can play on any device. Includes a marketplace where teachers can sell their creations.",
    logoUrl: "",
    websiteUrl: "https://www.tinytap.com",
    affiliateUrl: "",
    affiliateProgram: "",
    commissionRate: "",
    pricingTier: "Freemium",
    startingPrice: "Free",
    isFree: false,
    featured: false,
    rating: 4.4,
    reviewsCount: 1800,
    bestFor: ["Interactive Games", "Early Learning", "Student Activities"],
    subjects: ["All Subjects"],
    gradeLevels: ["Primary"],
    curriculum: ["International"],
    languages: ["English", "Multiple Languages"],
    categories: ["content-creation", "classroom-management"],
  },
]

module.exports = { categories, tools }
